version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_heap_max__size: 2G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  backend:
    build: ./server
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - neo4j

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/src:/app/src
    depends_on:
      - backend

volumes:
  neo4j_data:
  neo4j_logs: